/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.ucr.parchisproject.view;

/**
 *
 * @author Xpc
 */
public class GUITablero extends javax.swing.JFrame {
    
    /**
     * Creates new form GUITablero
     */
    public GUITablero() {
        initComponents();
    }

    public PanelControles getPanelControles() {
        return PanelControles;
    }

    public PanelTablero getPanelTablero() {
        return PanelTablero;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTablero = new cr.ucr.parchisproject.view.PanelTablero();
        PanelControles = new cr.ucr.parchisproject.view.PanelControles();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTablero.add(PanelControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, -1, -1));

        getContentPane().add(PanelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cr.ucr.parchisproject.view.PanelControles PanelControles;
    private cr.ucr.parchisproject.view.PanelTablero PanelTablero;
    // End of variables declaration//GEN-END:variables
}
