/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cr.ucr.parchisproject.view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Xpc
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        initComponents();
    }

    
    public void listen(ActionListener controller) {
        this.btnJugar.addActionListener(controller);
        this.btnHistorial.addActionListener(controller);
        this.btnInstruciones.addActionListener(controller);
        this.btnCreditos.addActionListener(controller);
    }
    
    
    public String getNombreJugador() {
        return jTFNombre.getText();
    }

    public String getColorSeleccionado() {
        return (String) jComboColor.getSelectedItem();
    }

    
    public JButton getBtnCreditos() {
        return btnCreditos;
    }

    public JButton getBtnHistorial() {
        return btnHistorial;
    }

    public JButton getBtnInstruciones() {
        return btnInstruciones;
    }

    public JButton getBtnJugar() {
        return btnJugar;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnInstruciones = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        jTFNombre = new javax.swing.JTextField();
        jComboColor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setBackground(new java.awt.Color(255, 0, 0));
        btnJugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJugar.setText("Jugar");
        add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 100, 60));

        btnHistorial.setBackground(new java.awt.Color(255, 255, 0));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistorial.setText("Historial");
        add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 100, 60));

        btnInstruciones.setBackground(new java.awt.Color(102, 255, 0));
        btnInstruciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInstruciones.setText("Instrucciones");
        add(btnInstruciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 110, 60));

        btnCreditos.setBackground(new java.awt.Color(0, 102, 204));
        btnCreditos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreditos.setText("Creditos");
        add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 100, 60));
        add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 100, -1));

        jComboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Amarillo", "Verde" }));
        add(jComboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Parchis");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoMenu.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnInstruciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JComboBox<String> jComboColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
