/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cr.ucr.parchisproject.view;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import cr.ucr.parchisproject.model.Ficha;
import cr.ucr.parchisproject.model.Jugador;
import java.awt.Dimension;

/**
 *
 * @author Xpc
 */
public class PanelTablero extends javax.swing.JPanel {

    private Image imagenTablero;
    private ArrayList<Jugador> jugadores;

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        
        jugadores = new ArrayList<>();
        
        setPreferredSize(new Dimension(1200, 1000));
        setMinimumSize(new Dimension(1200, 1000));
        setMaximumSize(new Dimension(1200, 1000));

        try {
            imagenTablero = ImageIO.read(getClass().getResource("/img/TableroJuego.png"));
        } catch (Exception e) {
            System.out.println("Error cargando tablero.png");
        }
    }

    public void setJugadores(ArrayList<Jugador> jugadores) {
        this.jugadores = jugadores;
    }

    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Dibujar tablero sin escalarlo
        if (imagenTablero != null) {
            g.drawImage(imagenTablero, 0, 0, 1200, 1000, this);
        }

        // Dibujar fichas
        if (jugadores != null) {
            for (Jugador jugador : jugadores) {
                for (Ficha ficha : jugador.getFichas()) {
                    Image imgFicha = ficha.getImagen();//Obtiene la imagen PNG asociada a la ficha
                    if (imgFicha != null) {
                        g.drawImage(imgFicha, ficha.getX() - 20, ficha.getY() - 20, 40, 40, this); //imagen, x, y, ancho, alto, observer, los -20 son para agarrar el centro exacto de la ficha
                    }
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
