/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cr.ucr.parchisproject.view;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

import cr.ucr.parchisproject.model.Ficha;
import cr.ucr.parchisproject.model.Jugador;

/**
 *
 * @author Xpc
 */
public class PanelTablero extends javax.swing.JPanel {

    private Image imagenTablero;
    private ArrayList<Jugador> jugadores;

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        
        jugadores = new ArrayList<>();

        try {
            imagenTablero = ImageIO.read(new File("resources/img/TableroJuego.png"));
        } catch (Exception e) {
            System.out.println("Error cargando tablero.png");
        }
    }

    public void setJugadores(ArrayList<Jugador> jugadores) {
        this.jugadores = jugadores;
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Dibujar tablero
        if (imagenTablero != null) {
            g.drawImage(imagenTablero, 0, 0, getWidth(), getHeight(), this);
        }

        // Dibujar fichas
        for (Jugador j : jugadores) {
            for (Ficha ficha : j.getFichas()) {
                if (ficha.getImagen() != null) {
                    g.drawImage(
                        ficha.getImagen(),
                        ficha.getX() - 16,
                        ficha.getY() - 16,
                        32, 32,
                        this
                    );
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
